<?php
/** @var \SendCloud\SendCloudV2\Block\Checkout\Config $block */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sendcloudv2servicepoint": {
                        "component": "SendCloud_SendCloudV2/js/view/checkout/shipping/servicePoint",
                        "scriptUrl": "<?= /* @escapeNotVerified */ $block->getScriptUrl()?>"
                    }
                }
            }
        }
    }
</script>
<?php if ($block->getIsActiveSCSkeleton()) : ?>
<?php // TODO: inject checkoutConfig with the deliveryOptions ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sendcloudv2skeleton": {
                        "component": "SendCloud_SendCloudV2/js/view/checkout/shipping/deliveryOptions",
                        "config": {
                            "checkoutConfig": {"test":"test"}
                        }
                    }
                }
            }
        }
    }
</script>
<?php endif; ?>
