<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sendcloudv2servicepoint": {
                        "component": "SendCloud_SendCloudV2/js/view/checkout/shipping/servicePoint",
                        "scriptUrl": "<?= /* @escapeNotVerified */ $block->getScriptUrl()?>"
                    }
                }
            }
        }
    }
</script>
