<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\AbstractOrder
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Escaper $escaper
 */

/** @var \Magento\Shipping\Helper\Data $shippingHelper */

use Magento\Sales\Api\Data\OrderExtensionInterface;

$shippingHelper = $block->getData('shippingHelper');
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
?>
<?php $order = $block->getOrder() ?>
<?php
/** @var OrderExtensionInterface $extensionAttributes */
$extensionAttributes = $order->getExtensionAttributes();
?>
<?php if ($order->getIsVirtual()):
    return '';
endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= $escaper->escapeHtml(__('Shipping &amp; Handling Information')) ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()): ?>
            <p>
                <a href="#" id="linkId" title="<?= $escaper->escapeHtmlAttr(__('Track Order')) ?>">
                    <?= $escaper->escapeHtml(__('Track Order')) ?>
                </a>
            </p>
            <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                'onclick',
                "popWin('" . $escaper->escapeJs($shippingHelper->getTrackingPopupUrlBySalesModel($order)) .
                "','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')",
                'a#linkId'
            ) ?>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <strong><?= $escaper->escapeHtml($order->getShippingDescription()) ?></strong>

            <?php if ($taxHelper->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?= /** @noEscape */ $_excl ?>
            <?php if ($taxHelper->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?= $escaper->escapeHtml(__('Incl. Tax')) ?> <?= /** @noEscape */ $_incl ?>)
            <?php endif; ?>

            <?php if ($extensionAttributes != null) : ?>
                <?php if ($extensionAttributes->getSendcloudData()) : ?>
                    <?php $sendCloudData = $extensionAttributes->getSendcloudData(); ?>
                    <div class="sendcloud-data">
                        <strong><?= $escaper->escapeHtml(__('Sendcloud Data')) ?></strong>
                        <div><?= $escaper->escapeHtml($sendCloudData->getCheckoutPayload()->getShippingProduct()->getName()) ?></div>
                        <div><?= $escaper->escapeHtml($sendCloudData->getCheckoutPayload()->getNominatedDayDelivery()->getFormattedDeliveryDate()) ?></div>
                    </div>
                <?php endif; ?>
                <?php if ($extensionAttributes->getSendcloudServicePointId() > 0) : ?>
                    <div class="service-point-information">
                        <strong><?= $escaper->escapeHtml(__('Service Point')) ?></strong>
                        <address>
                            <?= $escaper->escapeHtml($extensionAttributes->getSendcloudServicePointName()) ?><br>
                            <?= $escaper->escapeHtml($extensionAttributes->getSendcloudServicePointStreet()) ?> <?= $escaper->escapeHtml($extensionAttributes->getSendcloudServicePointHouseNumber()) ?><br>
                            <?= $escaper->escapeHtml($extensionAttributes->getSendcloudServicePointZipCode()) ?>  <?= $escaper->escapeHtml($extensionAttributes->getSendcloudServicePointCity()) ?><br>
                            <?= $escaper->escapeHtml($extensionAttributes->getSendcloudServicePointPostnumber()) ?>
                        </address>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('No shipping information available')) ?>
        <?php endif; ?>
    </div>
</div>
