<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\View */ ?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()) :
    return '';
endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Shipping &amp; Handling Information') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()) : ?>
            <p>
                <a href="#"
                   id="linkId"
                   onclick="popWin(
                       '<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')
                                                                ->getTrackingPopupUrlBySalesModel($order) ?>'
                       ,'trackorder','width=800,height=600,resizable=yes,scrollbars=yes')"
                   title="<?= /* @escapeNotVerified */ __('Track Order') ?>">
                    <?= /* @escapeNotVerified */ __('Track Order') ?>
                </a>
            </p>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()) : ?>
            <p>
                <strong><?= /* @escapeNotVerified */ $block->escapeHtml($order->getShippingDescription()) ?></strong>

                <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()) : ?>
                    <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
                <?php else : ?>
                    <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                <?php endif; ?>
                <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

                <?= /* @escapeNotVerified */ $_excl ?>
                <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl) : ?>
                    (<?= /* @escapeNotVerified */ __('Incl. Tax') ?> <?= /* @escapeNotVerified */ $_incl ?>)
                <?php endif; ?>
            </p>
        <?php //TODO: SC-19: Use the getSendCloudData() container to store the data ?>
        <?php if ($order->getSendCloudData() != null) : ?>
            <?php if ($order->getSendCloudData()->getSendcloudServicePointId() > 0) : ?>
                <div class="service-point-information">
                    <strong><?= __('Service Point') ?></strong>
                    <address>
                        <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointName() ?><br>
                        <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointStreet() ?> <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointHouseNumber() ?><br>
                        <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointZipCode() ?>  <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointCity() ?><br>
                        <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointPostnumber()?>
                    </address>
                </div>
            <?php endif; ?>


            <?php if ($order->getSendCloudData()->getSendcloudServicePointId() > 0) : ?>
                <div class="service-point-information">
                    <strong><?= __('Service Point') ?></strong>
                    <address>
                        <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointName() ?><br>
                        <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointStreet() ?> <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointHouseNumber() ?><br>
                        <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointZipCode() ?>  <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointCity() ?><br>
                        <?= /* @escapeNotVerified */ $order->getSendCloudData()->getSendcloudServicePointPostnumber()?>
                    </address>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <?php else : ?>
            <?= /* @escapeNotVerified */ __('No shipping information available') ?>
        <?php endif; ?>
    </div>
</div>
